<icecast>
    <location>$TARGET_LOCATION</location>
    <admin>$TARGET_ADMIN_EMAIL</admin>
    <limits>
        <clients>100</clients>
        <sources>8</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        <burst-on-connect>1</burst-on-connect>
        <burst-size>65535</burst-size>
    </limits>
    <authentication>
        <source-password>$SOURCE_PASSWORD</source-password>
        <relay-password>$RELAY_PASSWORD</relay-password>
        <admin-user>$TARGET_ADMIN_USER</admin-user>
        <admin-password>$ADMIN_PASSWORD</admin-password>
    </authentication>
    <hostname>$TARGET_HOSTNAME</hostname>
    <listen-socket>
        <port>8000</port>
    </listen-socket>
    <http-headers>
        <header name="Access-Control-Allow-Origin" value="*" />
    </http-headers>
    <relay>
	      <server>listen.noagendastream.com</server>
        <port>80</port>
        <mount>/noagenda</mount>
        <local-mount>/noagenda</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice3.somafm.com</server>
        <port>80</port>
        <mount>/groovesalad-256-mp3</mount>
        <local-mount>/groovesalad</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice3.somafm.com</server>
        <port>80</port>
        <mount>/secretagent-128-mp3</mount>
        <local-mount>/secretagent</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice3.somafm.com</server>
        <port>80</port>
        <mount>/suburbsofgoa-128-mp3</mount>
        <local-mount>/goa</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <fileserve>1</fileserve>
    <paths>
        <basedir>/usr/share/icecast2</basedir>
        <logdir>/var/log/icecast2</logdir>
        <webroot>/usr/share/icecast2/web</webroot>
        <adminroot>/usr/share/icecast2/admin</adminroot>
        <alias source="/" destination="/status.xsl"/>
    </paths>
    <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        <loglevel>4</loglevel> <!-- 4 Debug, 3 Info, 2 Warn, 1 Error -->
        <logsize>10000</logsize> <!-- Max size of a logfile -->
    </logging>
    <security>
        <chroot>0</chroot>
    </security>
</icecast>
