<icecast>
    <location>$TARGET_LOCATION</location>
    <admin>$TARGET_ADMIN_EMAIL</admin>
    <limits>
        <clients>100</clients>
        <sources>8</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        <burst-on-connect>1</burst-on-connect>
        <burst-size>65535</burst-size>
    </limits>
    <authentication>
        <source-password>$SOURCE_PASSWORD</source-password>
        <relay-password>$RELAY_PASSWORD</relay-password>
        <admin-user>$TARGET_ADMIN_USER</admin-user>
        <admin-password>$ADMIN_PASSWORD</admin-password>
    </authentication>
    <hostname>$TARGET_HOSTNAME</hostname>
    <listen-socket>
        <port>8000</port>
    </listen-socket>
    <http-headers>
        <header name="Access-Control-Allow-Origin" value="*" />
    </http-headers>
    <relay>
	      <server>listen.noagendastream.com</server>
        <port>80</port>
        <mount>/noagenda</mount>
        <local-mount>/noagenda</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/live-128-mp3</mount>
        <local-mount>/live</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/specials-128-mp3</mount>
        <local-mount>/specials</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/groovesalad-256-mp3</mount>
        <local-mount>/groovesalad</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/gsclassic-128-mp3</mount>
        <local-mount>/gsclassic</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/deepspaceone-128-mp3</mount>
        <local-mount>/deepspaceone</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/spacestation-128-mp3</mount>
        <local-mount>/spacestation</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/dronezone-256-mp3</mount>
        <local-mount>/dronezone</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/thetrip-128-mp3</mount>
        <local-mount>/thetrip</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/defcon-256-mp3</mount>
        <local-mount>/defcon</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/sonicuniverse-256-mp3</mount>
        <local-mount>/sonicuniverse</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/reggae-256-mp3</mount>
        <local-mount>/reggae</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/7soul-128-mp3</mount>
        <local-mount>/7soul</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/seventies-320-mp3</mount>
        <local-mount>/seventies</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/u80s-256-mp3</mount>
        <local-mount>/u80s</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/secretagent-128-mp3</mount>
        <local-mount>/secretagent</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/lush-128-mp3</mount>
        <local-mount>/lush</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/thistle-128-mp3</mount>
        <local-mount>/thistle</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/fluid-128-mp3</mount>
        <local-mount>/fluid</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/poptron-128-mp3</mount>
        <local-mount>/poptron</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/beatblener-128-mp3</mount>
        <local-mount>/beatblener</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/bootliquor-320-mp3</mount>
        <local-mount>/bootliquor</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/illstreet-128-mp3</mount>
        <local-mount>/illstreet</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/bagel-128-mp3</mount>
        <local-mount>/bagel</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/indiepop-128-mp3</mount>
        <local-mount>/indiepop</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/digitalis-128-mp3</mount>
        <local-mount>/digitalis</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/folkfwd-128-mp3</mount>
        <local-mount>/folkfwd</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/dubstep-256-mp3</mount>
        <local-mount>/dubstep</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/suburbsofgoa-128-mp3</mount>
        <local-mount>/goa</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/suburbsofgoa-128-mp3</mount>
        <local-mount>/suburbsofgoa</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/missioncontrol-128-mp3</mount>
        <local-mount>/missioncontrol</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/metal-128-mp3</mount>
        <local-mount>/metal</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/covers-128-mp3</mount>
        <local-mount>/covers</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <relay>
	      <server>ice$RANDOM_ICE.somafm.com</server>
        <port>80</port>
        <mount>/brfm-128-mp3</mount>
        <local-mount>/brfm</local-mount>
         <on-demand>1</on-demand>
    </relay>
    <fileserve>1</fileserve>
    <paths>
        <basedir>/usr/share/icecast2</basedir>
        <logdir>/var/log/icecast2</logdir>
        <webroot>/usr/share/icecast2/web</webroot>
        <adminroot>/usr/share/icecast2/admin</adminroot>
        <alias source="/" destination="/status.xsl"/>
    </paths>
    <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        <loglevel>4</loglevel> <!-- 4 Debug, 3 Info, 2 Warn, 1 Error -->
        <logsize>10000</logsize> <!-- Max size of a logfile -->
    </logging>
    <security>
        <chroot>0</chroot>
    </security>
</icecast>
